Отправляю задачи на проверку. Тесты прошли не все, но больше идей нет как поправить код.
js-tasks-ru/jsbasic-20210906-2_infestvw pull request #2
Opened 2021-09-15 20:54 UTC by Skor88

2021-09-15 20:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-16 20:12 UTC, SinimaWath requested changes

2021-09-16 20:12 UTC, SinimaWath commented on 1-module/2-task/index.js
> +    if (name.length < 4) {
Тебе сначала надо проверить на null или undefined.

Иначе если name == null, то в этом случае, вызов null.length - ломается

2021-09-16 20:12 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  if ( str.lenght > maxlength) {
str.length - у тебя lenght

2021-09-16 20:12 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
Давай упростим до одной строки, без лишних if: `return str.includes('1XBET') || str.includes('XXX')`

2021-09-19 16:00 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-19 16:01 UTC, Skor88 commented on 1-module/5-task/index.js
> +  if ( str.lenght > maxlength) {
Все задания поправил и запушил. 
Ведь несколько раз этот комментарий прочитал и не с первого раза увидел разницу )))

2021-09-19 17:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-19 18:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-19 19:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-19 19:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-20 20:23 UTC, SinimaWath requested changes
Надо еще решить 3 задачу 2 модуля, чтобы тесты прошли

2021-09-23 12:04 UTC, SinimaWath commented
У тебя есть конфликт в файле 2-module/3-task/index.js.

Сделай:
git pull upstream master
git status // так ты проверишь, где у тебя есть конфликты
Поправь файлик с конфликтами
git merge --continue // Потом сохраняешь название файла
git push origin master

Тут можно посмотреть пример
https://githowto.com/ru/resolving_conflicts

2021-09-25 15:28 UTC, SinimaWath commented
Давай поправим, то что я написал выше

2021-09-26 17:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-27 17:09 UTC, SinimaWath requested changes
Все ок, но надо решить 1 задачу 3 модуля, так как ты ее себе добавил

2021-09-29 19:25 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-29 20:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-10-03 14:54 UTC, SinimaWath approved these changes
теперь, все круто!

2021-10-03 14:55 UTC, merged